### ISSUE TITLE
ARM License VSC Keil studio vs uVision

### ISSUE THREAD

**Issue by vescovd1** [ARM-software/vscode-keil-studio-pack#11]
I have been evaluating the VSC Keil studio and been going back and forth between uVision 5 and Keil Visual Studio Code on Windows 10.
I understand the ARM licensing ... community or commercial is a blanket and covers the entire tool chain no matter which IDE (VSC or uVision) you use.
My test project compiles just fine under both uVision and Keil VSC (after migration ..of course) when I have the community license activated.
We also have a commercial 15 user floating license. The license server is on our network mapped Z drive.   
I deactivate the community license and reactivate the commercial license in the uVision License Managment tab for our commercial Floating License.
This works just fine when I recompile test project in the uVision IDE but if I do the same in Keil VSC I get ...

```

The C compiler

    "c:/Users/vescovd1/.vcpkg/artifacts/fd3d78d7/compilers.arm.armclang/6.20.0/bin/armclang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/GitHub/pss-prog-wireless-sidecom/Sidecom_Project/SidecomSTM32/tmp/Blinky/Device/Debug/CMakeFiles/CMakeScratch/TryCompile-g4vhwp
    
    Run Build Command(s):C:/Users/vescovd1/.vcpkg/artifacts/vcpkg-ce-default/tools.ninja.build.ninja/1.10.2/ninja.exe cmTC_892e0 && [1/2] Building C object CMakeFiles\cmTC_892e0.dir\testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_892e0.dir/testCCompiler.c.obj 
    c:\Users\vescovd1\.vcpkg\artifacts\fd3d78d7\compilers.arm.armclang\6.20.0\bin\armclang.exe   -mcpu=Cortex-M4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -o CMakeFiles\cmTC_892e0.dir\testCCompiler.c.obj -c C:\GitHub\pss-prog-wireless-sidecom\Sidecom_Project\SidecomSTM32\tmp\Blinky\Device\Debug\CMakeFiles\CMakeScratch\TryCompile-g4vhwp\testCCompiler.c
    armclang: error: Failed to check out a license.
    The license file could not be found. Check that ARMLMD_LICENSE_FILE is set correctly.
    armclang: note: 
ARMLMD_LICENSE_FILE is not set. You must set this to the path to your license.
    armclang: note: 
Information about this error is available at https://developer.arm.com/support/lic87/m1
     General licensing information is available at https://developer.arm.com/support/licensing/
     If you need further help, provide this complete error message to your supplier or to Arm via https://services.arm.com/support/s/contactsupport
     - ARMLMD_LICENSE_FILE: unset
     - LM_LICENSE_FILE: unset
     - ARM_PRODUCT_DEF: unset
     - ARM_PRODUCT_PATH: unset
     - ARM_TOOL_VARIANT: unset
     - Product location: c:\Users\vescovd1\.vcpkg\artifacts\fd3d78d7\compilers.arm.armclang\6.20.0\sw\mappings
     - Toolchain location: c:\Users\vescovd1\.vcpkg\artifacts\fd3d78d7\compilers.arm.armclang\6.20.0\bin
     - Selected tool variant: product
    armclang: note: 
 - Checkout feature: compiler5
     - Feature version: 5.0202302
     - Flex error code: -1
    Product: Arm Compiler for Embedded 6.20 Professional
    Component: Arm Compiler for Embedded 6.20
    Tool: armclang [5e9ad700]
    
    ninja: build stopped: subcommand failed.


```
I think I just need to set some of these environment variables ... but how, with what and where?

**Comment by jkrech** [comment]
Going forward you will get a User Based License (UBL) for MDK Professional which would enable both uVision and MDK6 VSCode.

The comment about the network drive sounds like a Keil floating license rather than FlexNet floating license. Can you please confirm?
For the time being I would suggest that you are registering the Arm Compiler from your Keil MDK installation instead of activating armclang using vcpkg/Environment Manager.

Please set the ENVIRONMENT VARIABLE in your system before launching VSCode:
```
  set AC6_TOOLCHAIN_6_20_0=c:\Keil_v5\ARM\ARMCLANG\bin
```
and remove the entry 
```
  "arm:compilers/arm/armclang": "^6.20.0"
```
from the vcpkg-configuration.json file in order to avoid that the registration is overwritten.

Now you are using the same Arm Compiler for Embedded toolchain within uVision as well as in VS Code.

Note: Toolchain registration for CMSIS-Toolbox is documented here:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#toolchain-registration

**Comment by vescovd1** [comment]
yes, we have the Keil Floating license.

**Comment by jkrech** [comment]
Good, with that in mind I had not suggested to set ARMLMD_LICENSE_FILE and ARM_TOOL_VARIANT, which only works for Flex Floating Licenses. 
Please let me know in case my proposed solution does not work for you.

**Comment by vescovd1** [comment]
looks like that worked!  Thank you.
