### ISSUE TITLE
Click on "Create new solution" to  prompts network error。

### ISSUE THREAD

**Issue by haiqinJack** [ARM-software/vscode-keil-studio-pack#21]
**Describe the bug**
- OS and Version: MacOS 12.6
- VS Code Version: 1.89.1
- Extension Version: v1.18.2
- A clear and concise description of what the bug is. Click on "Create new solution" to  prompts network error。
﻿
![1233](https://github.com/ARM-software/vscode-keil-studio-pack/assets/35925781/e4ffda92-b5f8-4601-8206-2a77d18f384b)

**Comment by mcgordonite** [comment]
I'm closing this in favour of https://github.com/ARM-software/vscode-cmsis-csolution/issues/67.
