### ISSUE TITLE
J-Link support & Manually install package & Configuration wizard display

### ISSUE THREAD

**Issue by Deadline039** [ARM-software/vscode-keil-studio-pack#24]
1. Currently, only ULINK, ST-Link and DAP are supported. I usually use J-Link for downloading and debugging. 
2. For some reason, github cannot be connected correctly in Chinese mainland. Can I manually install the CMSIS software package?
3. The configuration wizard display is a very useful tool for setting configuration items. Can this feature be added in future versions?

**Comment by jkrech** [comment]
1. Note that you configure J-Link to run in CMSIS-DAP mode
2. Public CMSIS Software Packs can be download from https://www.keil.arm.com/packs/ or using cpackget from [CMSIS-Toolbox](https://www.keil.arm.com/artifacts/#tools/open-cmsis-pack/cmsis-toolbox) 
3. The configuration wizard view is already available in the current versions of Arm CMSIS Solution Extension. If you open a file with config wizard annotation: `//-------- <<< Use Configuration Wizard in Context Menu >>> --------------------` in VSCode
you can click on the "Open Preview" icon 
![image](https://github.com/user-attachments/assets/06a27d3a-c1f8-475a-b17a-defc1024cc23)
to open the graphical view.

**Comment by Deadline039** [comment]
> 1. Note that you configure J-Link to run in CMSIS-DAP mode
> 2. Public CMSIS Software Packs can be download from https://www.keil.arm.com/packs/ or using cpackget from [CMSIS-Toolbox](https://www.keil.arm.com/artifacts/#tools/open-cmsis-pack/cmsis-toolbox)
> 3. The configuration wizard view is already available in the current versions of Arm CMSIS Solution Extension. If you open a file with config wizard annotation: `//-------- <<< Use Configuration Wizard in Context Menu >>> --------------------` in VSCode
>    you can click on the "Open Preview" icon ![image](https://private-user-images.githubusercontent.com/8290187/355123330-06a27d3a-c1f8-475a-b17a-defc1024cc23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzExMDYsIm5iZiI6MTcyMjkzMDgwNiwicGF0aCI6Ii84MjkwMTg3LzM1NTEyMzMzMC0wNmEyN2QzYS1jMWY4LTQ3NWEtYjE3YS1kZWZjMTAyNGNjMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMDc1MzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTA3NGRlMGNiMDg2ZDA3YzA5ODVhNTJlNDhmNzZmMTljY2EyN2QyZjI3NjViYmIwMmRmZTVkZGEwNDNjMGI0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PnhffSXdOIa4LaHiL202eJIS2HJg0otWv4K6t9gBhP0) to open the graphical view.

Thanks for your reply.
