### ISSUE TITLE
When the project configuration file is not in the root directory of vscode's workspace, it will not build.

### ISSUE THREAD

**Issue by HalfSweet** [ARM-software/vscode-keil-studio-pack#3]
Type: Bug Report

**Describe the bug**
- Desktop or Web: Desktop
- OS and Version: Windows 11 22H2 22621.1992
- VS Code Version:1.80.1
- Extension Version:1.7.7
- Target Device:STM32F030C8Tx
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

In general, when using the `STM32CubeMX` software to generate an MDK project, the typical file path looks like this
```
.
│ .mxproject
│ f030test.ioc
│
├──.vscode
│ settings.json
│ ├──.vscode │ settings.json │ ├──.
├───Core
│ ├───Inc
│ │ xxx.h
│ │
│ └──Src
│ xxx.c
│
├───Drivers
│ ├───CMSIS
│ │ xxx
│ │
│ └───STM32F0xx_HAL_Driver
│ │
│ ├───Inc
│ │ │ xxx
│ │
│ └──Src
│ xxx
│
└──MDK-ARM
    │ .clangd
    │ f030test.cproject.yaml
    │ f030test.csolution.yaml
    │ f030test.uvguix.HalfSweet
    │ f030test.uvoptx
    │ f030test.uvprojx
    │ f030test_f030test.sct
    │ startup_stm32f030x8.s
    │ vcpkg-configuration.json
    │
    ├──.vscode
    │ launch.json
    │ tasks.json
    │ vscode │ vcpkg-configuration.json │ tasks.json
    ├───DebugConfig
    │ xxx
    └───RTE
        └───xxx
```
But this poses a problem, when we use the outermost folder as the root directory of the workspace, the plugin will not be able to do the build job.
Of course, we can set `MDK-ARM` as the root directory of the workspace, but since the rest of the code files will be leveled with it, we can't do a good job of managing the whole project.

Terminal output:
```
 *  正在执行任务: CMSIS Build 

spawn cbuild ENOENT

 *  终端进程启动失败(退出代码: 1)。 
 *  终端将被任务重用，按任意键关闭。 
```

**To Reproduce**
1. Set the root directory of the workspace to the same level as the `,ioc` file.
2. Click on the `build` button in CMSIS

**Expected behavior**
I want to build a project that manages any subdirectory in the root directory of the workspace.

**Code sample and logs**
- `launch.json`
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Embedded Debug",
            "type": "embedded-debug",
            "request": "launch",
            "program": "${command:embedded-debug.getApplicationFile}",
            "serialNumber": "${command:device-manager.getSerialNumber}",
            "cmsisPack": "${command:device-manager.getDevicePack}",
            "debugFrom": "main",
        }
    ]
}
```

**Screenshots**

![图片](https://github.com/ARM-software/vscode-keil-studio-pack/assets/60973476/450f42fd-061d-48ce-b552-2fc955b88fb2)

**Additional context**

**Comment by mcgordonite** [comment]
Hi @HalfSweet, the cause of this issue is that the extension only activates the vcpkg environment automatically when the vcpkg-configuration.json is at the root of the workspace.

You can manually activate the environment by right clicking on the vcpkg-configuration.json file in the file explorer, and click "Activate vcpkg environment.

Once that completes, the build task should be able to find the build tools.

**Comment by HalfSweet** [comment]
This worked and solved my problem, thanks a lot!
