### ISSUE TITLE
.cpp files are not supported for uVision project conversion

### ISSUE THREAD

**Issue by GeorgePriestner-Eaton** [ARM-software/vscode-keil-studio-pack#4]
Type: Feature Request

I am attempting to convert a uVision .uvprojx file to a csolution file.
Extension version: 1.7.8

I get the error:
.cpp Extension .cpp is not supported.

when attempting to convert a uVision project to csolution project.

![image](https://github.com/ARM-software/vscode-keil-studio-pack/assets/99959954/759bd9f9-d9d1-4246-ac31-f74e72fe4579)

**Comment by jkrech** [comment]
@GeorgePriestner-Eaton for your information, C++ support is in our backlog for the uv2csolution converter and is targeted for our next minor version update (1.1.0) in the coming months. Given the summer vacation season I am unable to give you a more specific timeline at the moment. Sorry for the trouble this is causing you.

**Comment by MarkWannaFly** [comment]
I'm having the same problem with version 1.10.0. When will it be fixed?

**Comment by MarkWannaFly** [comment]
> @GeorgePriestner-Eaton for your information, C++ support is in our backlog for the uv2csolution converter and is targeted for our next minor version update (1.1.0) in the coming months. Given the summer vacation season I am unable to give you a more specific timeline at the moment. Sorry for the trouble this is causing you.

I'm having the same problem with version 1.10.0. When will it be fixed?

**Comment by hqp37** [comment]
> @GeorgePriestner-Eaton for your information, C++ support is in our backlog for the uv2csolution converter and is targeted for our next minor version update (1.1.0) in the coming months. Given the summer vacation season I am unable to give you a more specific timeline at the moment. Sorry for the trouble this is causing you.

Like @MarkWannaFly, I also have the same problem, unable to convert from uvprojx project with .cpp file to csolution project, with version 1.10.0.

**Comment by mcgordonite** [comment]
Version 1.6.0 of the Csolution extension adds support for converting µVision projects with C++ files.
