### ISSUE TITLE
What is the correct location to report problems?

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-keil-studio-pack#5]
The VS Code version of MDK6 Community seems to have many places to report issues.  
What is the correct location? 
How can I find as a user this location?

**Comment by mcgordonite** [comment]
The GitHub issues page for the extension in question is the best place to report an issue. If you're not sure which extension is affected, you can report an issue on this extension pack repository for triage.

There are several ways you are pointed to the issues pages:
- The VS Code Marketplace has an "issues" link:
        ![Marketplace](https://github.com/ARM-software/vscode-keil-studio-pack/assets/12599255/a0bdceba-f046-4617-ada9-261fee43b931)
- The READMEs have a "submit feedback" section:
        ![README](https://github.com/ARM-software/vscode-keil-studio-pack/assets/12599255/4005105d-cebd-4899-9b52-c74c810d5c38)

When you start a new issue, I've updated the issue templates to hopefully make things clearer:
![Issue Template](https://github.com/ARM-software/vscode-keil-studio-pack/assets/12599255/bce16299-2d9e-466f-a70c-fc0bf0e65726)

**Comment by mcgordonite** [comment]
There is now a page dedicated to answering this question: https://www.keil.arm.com/support/. The extensions link here to help users decide.
