### ISSUE TITLE
Support for uVision 5.xx

### ISSUE THREAD

**Issue by SM-Kleemann** [ARM-software/vscode-keil-studio-pack#7]
Type: Feature Request

We are using uVision 5.27 and it would be great if we could VSCode as front end and still using ARM toolchain.

Thank you.

**Comment by jkrech** [comment]
When you refer to "ARM toolchain" could you be a bit more precise?
Assuming you simply want to continue to use the Arm Compiler Version 6.18 using your current Keil MDK license, this can be achieved.

The CMSIS-Toolbox backend used by the Arm CMSIS csolution VSCode extension allows you to [register toolchains](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#toolchain-registration)

MDK 5.37 ships with Arm Compiler Version 6.18.0

```
  set AC6_TOOLCHAIN_6_18_0=c:\Keil_v5\ARM\ARMCLANG\bin
```
Note: run the command 
```
  csolution list toolchains -v
```
to see which toolchain versions you can select from and where they are installed.

**Comment by chrsw** [comment]
We use Keil MDK version 5.38 with Arm C compiler V5.06 update 6 (build 750). We had to install this specific compiler after installing Keil MDK 5.38. We cannot change compilers. I noticed on https://learn.arm.com/learning-paths/microcontrollers/uvprojx-conversion/ it says "Arm Compiler 5 is not supported." Is that the end and final answer? No support for using MDK projects on VS Code if you're using version 5 of armcc.exe?

**Comment by ha11otronix** [comment]
Is it possible to have C51 compiler support in VSCode extension? If already have can anydbody guide me the documentation?
right now I am using uVision 5 and C51 compiler.

**Comment by jkrech** [comment]
> We use Keil MDK version 5.38 with Arm C compiler V5.06 update 6 (build 750). We had to install this specific compiler after installing Keil MDK 5.38. We cannot change compilers. I noticed on https://learn.arm.com/learning-paths/microcontrollers/uvprojx-conversion/ it says "Arm Compiler 5 is not supported." Is that the end and final answer? No support for using MDK projects on VS Code if you're using version 5 of armcc.exe?

Please excuse the delay in response. Yes, it is the final answer, that there is no plans to support Arm Compiler 5 in CMSIS-Toolbox and VSCode. Note that Arm Compiler 5 is not supported since a long time.

**Comment by jkrech** [comment]
> Is it possible to have C51 compiler support in VSCode extension? If already have can anydbody guide me the documentation? right now I am using uVision 5 and C51 compiler.

There is no plans to develop a VSCode extension supporting Keil C51 toolchain.
